### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by jmarhee** [packet-labs/packet-tanzu-tf#3]
Use the Terraform Drone template from multiarch-k8s

**Comment by rainleander** [comment]
Is it possible to get this one figured out in the next week? If not, how can I help?

**Comment by jmarhee** [comment]
There's a lot of this process which remains manual, so it cannot, at this time, be automated end to end for the purposes of testing, and not without maintaining certain parts of the infrastructure persistently (i.e. the object store for the installation media). I will see what some potential alternatives are (if even validating the the terraform plans themselves is possible without these things)

**Comment by rainleander** [comment]
That's fair; thx @jmarhee

**Comment by rainleander** [comment]
How can I help with this?

**Comment by jmarhee** [comment]
I've kept this issue in mind, so there's one major issue that prevents this from happening and having the tests be useful:

Two components in this require ISOs to install the software which other components depend on, and this requires additional infrastructure for object storage (which can't be automated-- we can spin up the minio module in this, but there's no automated way to get, for example, NSX and vSphere ISOs from VMWare at present, so this is a manual prerequisite for the entire project-- testing this automatically would require leaving this infrastructure in place, which I guess is doable)

However, to get something in place at all, I'm going to suggest that we, at least, validate Terraform, which I can add to the PR in progress now for splitting these modules apart.

**Comment by jmarhee** [comment]
Okay, so I've added the following to validate Terraform, and at least get something of a status on this in place:

https://github.com/packet-labs/packet-tanzu-tf/blob/main/.drone.yml

The build status is added to the other indicators in the README.

**Comment by rainleander** [comment]
WFM!
